### ISSUE TITLE
fail to import paper-swatch-picker-content 

### ISSUE THREAD

**Issue by hitokiri8x** [IswPolymerElements/isw-color-input#3]
Hello,  just after importing your picker an error is triggered from
`<link rel="import" href="../paper-swatch-picker/paper-swatch-picker-content.html">
`
because that files does not exist, also checked  in the official repo of swatch-picker

**Comment by rene-lindner-isw** [comment]
Thanks for your feedback!
Did you install the element via bower?
Have you previously installed the paper-swatch-picker?

The isw-color-input element depends on a fork of the paper-swatch-picker, the official picker has no paper-swatch-picker-content element, and i'm getting no feedback about a merge atm.

https://github.com/PolymerElements/paper-swatch-picker/issues/11

Try uninstalling the original paper-swatch-picker, and then reinstalling the isw-color-input, which should also install the forked paper-swatch-picker as dependency.

**Comment by hitokiri8x** [comment]
Yeah I installed via bower and had the "original" version of paper-swatch-picker. 
now after a clean-up works! ;)
